# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aa07cce258996932ea5880c8bcb0fbd43a807eb3123ed13ccb47c6c950a72f4d127b7408ae5d8636398320cb285de64f8e2a553321c4d52deb973948a995a1bc

test:
  secret_key_base: 185659c2bab54b56b0c7fc1e1aa377907649b0df6ecbd2a945d6608d1695df3a0e2b202b2066b4fef3f6dc328ac582df4fed4d0a1d21e872dcdf78e9d71369e6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
